name: Publish UPM Package

on:
  push:
    tags:        
      - v*
   
jobs:
  upm-release-essential:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: quabug/create-upm-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upm_package_path: .
        upm_tag_prefix: v
    - uses: actions/upload-artifact@v2
      if: always()
      with:
        name: Test results
        path: artifacts
